name: Output random value
on:
  push:
    branches:
      - "**output**"

jobs:
  output_random:
    runs-on: ubuntu-latest
    outputs:
      # "generate-random"というidのstepの、hogeという名前のものをfugaとしてアウトプットする
      fuga: ${{ steps.generate-random.outputs.hoge }}
    steps:
      - id: generate-random
        run: echo "::set-output name=hoge::$(openssl rand -base64 12)"
  receive_output_and_echo:
    runs-on: ubuntu-latest
    needs: output_random
    steps:
      - run: echo "${{ needs.output_random.outputs.fuga }}"
